#!/bin/bash

############################# First window ##############################
byobu new-window -n deploy

############################ Second window ##############################
byobu split-window -v
byobu select-layout tiled

############################# Third window ##############################
byobu split-window -h
byobu select-layout tiled

############################# Forth window ##############################
byobu split-window -v
byobu select-layout tiled

############################# Fifth window ##############################
byobu split-window -h
byobu select-layout tiled

############################# Sixth window ##############################
byobu split-window -v
byobu select-layout tiled

#byobu select-layout "aff9,169x41,0,0{84x41,0,0[84x4,0,0,1,84x15,0,5,6,84x15,0,21,4,84x4,0,37,5],84x41,85,0[84x20,85,0,2,84x20,85,21,3]}"

############################# Seventh window ############################
byobu split-window -v
byobu select-layout "dae7,169x41,0,0{84x41,0,0[84x4,0,0{42x4,0,0,3,41x4,43,0,9},84x15,0,5,4,84x15,0,21,5,84x4,0,37,6],84x41,85,0[84x20,85,0,7,84x20,85,21,8]}"

sleep 2

byobu send-keys -t 0 "printf '\033]2;Alice machine\033\\'" ENTER
byobu send-keys -t 1 "printf '\033]2;Bob machine\033\\'" ENTER
byobu send-keys -t 2 "printf '\033]2;Alice node\033\\'" ENTER
byobu send-keys -t 3 "printf '\033]2;Bob node\033\\'" ENTER
byobu send-keys -t 4 "printf '\033]2;Ganache\033\\'" ENTER
byobu send-keys -t 5 "printf '\033]2;Alice Monitor\033\\'" ENTER
byobu send-keys -t 6 "printf '\033]2;Bob Monitor\033\\'" ENTER

byobu set -g pane-border-status top
byobu set -g pane-border-format " #{pane_title} "


export RUST_LOG=dispatcher=trace,transaction=trace,configuration=trace,utils=trace,state=trace,compute=trace,hasher=trace
byobu send-keys -t 2 "export RUST_LOG=$RUST_LOG" ENTER
byobu send-keys -t 3 "export RUST_LOG=$RUST_LOG" ENTER

byobu send-keys -t 5 "# Wait to start machine managers... "
byobu send-keys -t 0 "./execute_machine_manager_ephemeral_container.sh" ENTER
byobu send-keys -t 1 "./execute_defective_machine_manager_ephemeral_container.sh" ENTER
byobu send-keys -t 5 "machine managers started." ENTER

sleep 6

byobu send-keys -t 5 "workon vir" ENTER
byobu send-keys -t 5 "python initialize_machine.py -c" ENTER
byobu send-keys -t 6 "workon vir" ENTER
byobu send-keys -t 6 "python initialize_machine.py -c -a localhost:50052 -o out_defective" ENTER

sleep 6

echo -n "Starting Ganache..."
byobu send-keys -t 5 "# Wait to start Ganache... "
byobu send-keys -t 4 "cd blockchain-node && ./execute_cartesi_blockchain_node_ephemeral_container.sh" ENTER
sleep 30s
echo " Ganache ready."
byobu send-keys -t 5 "Ganache ready." ENTER

echo -n "Moking instances..."
byobu send-keys -t 5 "# Wait to mock instances..."
byobu send-keys -t 2 "./mock_instances.js" ENTER
echo " instantiation finished."
byobu send-keys -t 5 "mocking finished" ENTER "clear" ENTER

byobu send-keys -t 2 "./execute_ephemeral_alice_compute_container.sh" ENTER
byobu send-keys -t 3 "./execute_ephemeral_bob_compute_container.sh" ENTER

byobu send-keys -t 5 "#should start the watcher" ENTER
byobu send-keys -t 5 "#workon vir2" ENTER
byobu send-keys -t 5 "#python watcher.py"
byobu send-keys -t 6 "exit" ENTER
