#!/bin/bash

############################# First window ##############################
byobu new-window -n deploy

############################ Second window ##############################
byobu split-window -v
byobu select-layout tiled

############################# Third window ##############################
byobu split-window -h
byobu select-layout tiled

############################# Forth window ##############################
byobu split-window -v
byobu select-layout tiled

############################# Fifth window ##############################
byobu split-window -h
byobu select-layout tiled

############################# Sixth window ##############################
byobu split-window -v
byobu select-layout tiled

#byobu select-layout "aff9,169x41,0,0{84x41,0,0[84x4,0,0,1,84x15,0,5,6,84x15,0,21,4,84x4,0,37,5],84x41,85,0[84x20,85,0,2,84x20,85,21,3]}"

############################# Seventh window ############################
byobu split-window -v
byobu select-layout "dae7,169x41,0,0{84x41,0,0[84x4,0,0{42x4,0,0,3,41x4,43,0,9},84x15,0,5,4,84x15,0,21,5,84x4,0,37,6],84x41,85,0[84x20,85,0,7,84x20,85,21,8]}"

sleep 2s

byobu send-keys -t 0 "printf '\033]2;Alice machine\033\\'" ENTER
byobu send-keys -t 1 "printf '\033]2;Bob machine\033\\'" ENTER
byobu send-keys -t 2 "printf '\033]2;Alice node\033\\'" ENTER
byobu send-keys -t 3 "printf '\033]2;Bob node\033\\'" ENTER
byobu send-keys -t 4 "printf '\033]2;Ganache\033\\'" ENTER
byobu send-keys -t 5 "printf '\033]2;Alice Monitor\033\\'" ENTER
byobu send-keys -t 6 "printf '\033]2;Bob Monitor\033\\'" ENTER

byobu set -g pane-border-status top
byobu set -g pane-border-format " #{pane_title} "

byobu send-keys -t 5 "# Wait to start machine managers... "
byobu send-keys -t 0 "./execute_machine_manager_ephemeral_container.sh" ENTER
byobu send-keys -t 1 "./execute_defective_machine_manager_ephemeral_container.sh" ENTER
byobu send-keys -t 5 "machine managers started." ENTER

sleep 10s

echo -n "Starting Ganache..."
byobu send-keys -t 5 "# Wait to start Ganache... "
byobu send-keys -t 4 "cd blockchain-node && ./execute_cartesi_blockchain_node_ephemeral_container.sh" ENTER
sleep 10s
echo " Ganache ready."
byobu send-keys -t 5 "Ganache ready." ENTER

byobu send-keys -t 5 "# Building demo dapp image if needed (this may take some minutes)... "
#Build demo-dapp-image
./build_demo_dapp_image.sh
byobu send-keys -t 5 " Done." ENTER

sleep 5s

MM_ADD=`docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ephemeral-machine-manager`
DEFECTIVE_MM_ADD=`docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ephemeral-defective-machine-manager`

byobu send-keys -t 5 "./execute_initialize_machine_through_docker.sh $MM_ADD" ENTER
byobu send-keys -t 6 "./execute_initialize_defective_machine_through_docker.sh $DEFECTIVE_MM_ADD" ENTER

sleep 15s

byobu send-keys -t 6 "#Creating compute config files ..."
#Creating Alice config file
byobu send-keys -t 5 "./make_alice_dispatcher_config.sh" ENTER
#Creating Bob config file
sleep 15s
byobu send-keys -t 5 "./make_bob_dispatcher_config.sh" ENTER
sleep 15s
byobu send-keys -t 6 "# Done" ENTER

ETH_NODE_ADD=`docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ephemeral-cartesi-blockchain-node`

echo -n "Moking instances..."
byobu send-keys -t 5 "# Wait to mock instances..."
byobu send-keys -t 2 "./execute_mock_instances_through_docker.sh $ETH_NODE_ADD" ENTER
sleep 10
echo " instantiation finished."
byobu send-keys -t 5 "mocking finished" ENTER "clear" ENTER

byobu send-keys -t 2 "./execute_ephemeral_alice_compute_container.sh" ENTER
byobu send-keys -t 3 "./execute_ephemeral_bob_compute_container.sh" ENTER

byobu send-keys -t 5 "#should start the watcher" ENTER
byobu send-keys -t 5 "#workon vir2" ENTER
byobu send-keys -t 5 "#python watcher.py"
byobu send-keys -t 6 "exit" ENTER
